import { ClassItem, UserProfile } from '../types';

export const DEFAULT_USER: UserProfile = {
  id: 'usr_2026_01',
  name: 'Varsha Korabu',
  email: 'varshakorabu56@gmail.com',
  role: 'student',
  department: 'Computer Science & Engineering',
  semester: 'Semester 6',
  studentId: 'CS-2026-8941',
};

export const INITIAL_CLASSES: ClassItem[] = [
  // Monday classes from prompt example
  {
    id: 'cls_mon_1',
    day: 'Monday',
    startTime: '09:00',
    endTime: '10:00',
    subject: 'Database Management Systems (DBMS)',
    subjectCode: 'CS301',
    faculty: 'Dr. Robert Vance',
    room: 'Room 201',
    color: '#3b82f6', // blue
    type: 'lecture',
  },
  {
    id: 'cls_mon_2',
    day: 'Monday',
    startTime: '10:00',
    endTime: '11:00',
    subject: 'Artificial Intelligence (AI)',
    subjectCode: 'CS402',
    faculty: 'Prof. Alan Thorne',
    room: 'Lab 2',
    color: '#8b5cf6', // purple
    type: 'lab',
  },
  {
    id: 'cls_mon_3',
    day: 'Monday',
    startTime: '11:00',
    endTime: '12:00',
    subject: 'Computer Networks (CN)',
    subjectCode: 'CS304',
    faculty: 'Dr. Elena Rostova',
    room: 'Room 305',
    color: '#10b981', // emerald
    type: 'lecture',
  },

  // Tuesday
  {
    id: 'cls_tue_1',
    day: 'Tuesday',
    startTime: '09:30',
    endTime: '11:00',
    subject: 'Machine Learning & Neural Networks',
    subjectCode: 'CS410',
    faculty: 'Dr. Priya Sharma',
    room: 'Auditorium B',
    color: '#ec4899', // pink
    type: 'lecture',
  },
  {
    id: 'cls_tue_2',
    day: 'Tuesday',
    startTime: '11:30',
    endTime: '13:00',
    subject: 'Cloud Computing Architecture',
    subjectCode: 'CS415',
    faculty: 'Prof. Kenneth Cole',
    room: 'Room 108',
    color: '#06b6d4', // cyan
    type: 'lecture',
  },

  // Wednesday (including AI class that user can move to Friday at 2 PM)
  {
    id: 'cls_wed_1',
    day: 'Wednesday',
    startTime: '10:00',
    endTime: '11:30',
    subject: 'Artificial Intelligence (AI)',
    subjectCode: 'CS402',
    faculty: 'Prof. Alan Thorne',
    room: 'Lab 2',
    color: '#8b5cf6',
    type: 'lab',
  },
  {
    id: 'cls_wed_2',
    day: 'Wednesday',
    startTime: '14:00',
    endTime: '15:30',
    subject: 'Software Engineering & Agile Labs',
    subjectCode: 'CS308',
    faculty: 'Dr. Sarah Connor',
    room: 'Lab 5',
    color: '#f59e0b', // amber
    type: 'lab',
  },

  // Thursday
  {
    id: 'cls_thu_1',
    day: 'Thursday',
    startTime: '09:00',
    endTime: '10:30',
    subject: 'Operating Systems & Kernels',
    subjectCode: 'CS305',
    faculty: 'Dr. Marcus Vance',
    room: 'Room 204',
    color: '#6366f1', // indigo
    type: 'lecture',
  },
  {
    id: 'cls_thu_2',
    day: 'Thursday',
    startTime: '13:00',
    endTime: '14:30',
    subject: 'Cyber Security & Cryptography',
    subjectCode: 'CS420',
    faculty: '', // purposely missing faculty to demonstrate missing info detection
    room: 'Room 305',
    color: '#ef4444', // red
    type: 'lecture',
  },

  // Friday
  {
    id: 'cls_fri_1',
    day: 'Friday',
    startTime: '10:00',
    endTime: '11:30',
    subject: 'Mobile Application Development',
    subjectCode: 'CS425',
    faculty: 'Prof. Lisa Wang',
    room: '', // purposely missing room to demonstrate "⚠️ Room information unavailable."
    color: '#14b8a6', // teal
    type: 'lecture',
  },
  {
    id: 'cls_fri_2',
    day: 'Friday',
    startTime: '15:00',
    endTime: '16:30',
    subject: 'Seminar on Generative AI',
    subjectCode: 'CS490',
    faculty: 'Dean Montgomery',
    room: 'Main Hall',
    color: '#8b5cf6',
    type: 'seminar',
  },
  // Division C Parallel Labs (Batch C1 & C2)
  {
    id: 'cls_tue_c1_lab',
    day: 'Tuesday',
    startTime: '14:00',
    endTime: '16:00',
    subject: 'Parallel Computing Lab',
    subjectCode: 'CS412L',
    faculty: 'Prof. David Kuck',
    room: 'Narendra Karmakar Lab (First Floor)',
    color: '#3b82f6',
    type: 'lab',
    batch: 'C1',
    division: 'Division C',
    notes: 'Batch C1 hands-on cluster computing',
  },
  {
    id: 'cls_tue_c2_lab',
    day: 'Tuesday',
    startTime: '14:00',
    endTime: '16:00',
    subject: 'Internet of Things (IoT) Lab',
    subjectCode: 'CS418L',
    faculty: 'Dr. Anita Desai',
    room: 'E Balaguruswamy Lab (First Floor)',
    color: '#8b5cf6',
    type: 'lab',
    batch: 'C2',
    division: 'Division C',
    notes: 'Batch C2 embedded sensor networking',
  },
];

export const SAMPLE_TIMETABLES: Array<{
  id: string;
  title: string;
  description: string;
  classes: ClassItem[];
}> = [
  {
    id: 'sample_div_c',
    title: 'Division C (Batches C1 & C2)',
    description: 'Division C schedule with parallel labs: C1 Parallel Computing & C2 IoT Lab',
    classes: INITIAL_CLASSES,
  },
  {
    id: 'sample_div_b',
    title: 'Division B (Batches B1 & B2)',
    description: 'Division B schedule with parallel labs: B1 Cloud Architecture & B2 Big Data Analytics',
    classes: [
      {
        id: 'b_mon_1',
        day: 'Monday',
        startTime: '09:00',
        endTime: '10:00',
        subject: 'Database Management Systems (DBMS)',
        subjectCode: 'CS301',
        faculty: 'Dr. Robert Vance',
        room: 'Room 202',
        color: '#3b82f6',
        type: 'lecture',
        division: 'Division B',
      },
      {
        id: 'b_mon_2',
        day: 'Monday',
        startTime: '10:00',
        endTime: '11:00',
        subject: 'Operating Systems & System Calls',
        subjectCode: 'CS305',
        faculty: 'Dr. Marcus Vance',
        room: 'Room 202',
        color: '#6366f1',
        type: 'lecture',
        division: 'Division B',
      },
      {
        id: 'b_tue_lab_b1',
        day: 'Tuesday',
        startTime: '14:00',
        endTime: '16:00',
        subject: 'Cloud Computing Architecture Lab',
        subjectCode: 'CS415L',
        faculty: 'Prof. Kenneth Cole',
        room: 'Ada Lovelace Lab (Second Floor)',
        color: '#06b6d4',
        type: 'lab',
        batch: 'B1',
        division: 'Division B',
        notes: 'Batch B1 Cloud cluster deployment',
      },
      {
        id: 'b_tue_lab_b2',
        day: 'Tuesday',
        startTime: '14:00',
        endTime: '16:00',
        subject: 'Big Data Analytics Lab',
        subjectCode: 'CS419L',
        faculty: 'Dr. Sarah Connor',
        room: 'Alan Turing Lab (Second Floor)',
        color: '#10b981',
        type: 'lab',
        batch: 'B2',
        division: 'Division B',
        notes: 'Batch B2 Hadoop and Spark pipelines',
      },
      {
        id: 'b_wed_1',
        day: 'Wednesday',
        startTime: '11:00',
        endTime: '12:30',
        subject: 'Computer Networks (CN)',
        subjectCode: 'CS304',
        faculty: 'Dr. Elena Rostova',
        room: 'Room 202',
        color: '#10b981',
        type: 'lecture',
        division: 'Division B',
      },
      {
        id: 'b_thu_1',
        day: 'Thursday',
        startTime: '10:00',
        endTime: '11:30',
        subject: 'Mobile Application Development',
        subjectCode: 'CS425',
        faculty: 'Prof. Lisa Wang',
        room: 'Room 202',
        color: '#14b8a6',
        type: 'lecture',
        division: 'Division B',
      },
    ],
  },
  {
    id: 'sample_div_a',
    title: 'Division A (Batches A1 & A2)',
    description: 'Division A schedule with parallel labs: A1 Advanced Algorithms & A2 Cyber Security',
    classes: [
      {
        id: 'a_mon_1',
        day: 'Monday',
        startTime: '09:00',
        endTime: '10:00',
        subject: 'Database Management Systems (DBMS)',
        subjectCode: 'CS301',
        faculty: 'Dr. Robert Vance',
        room: 'Room 101',
        color: '#3b82f6',
        type: 'lecture',
        division: 'Division A',
      },
      {
        id: 'a_tue_lab_a1',
        day: 'Tuesday',
        startTime: '14:00',
        endTime: '16:00',
        subject: 'Advanced Algorithms & Graph Lab',
        subjectCode: 'CS401L',
        faculty: 'Dr. Priya Sharma',
        room: 'Linus Torvalds Lab (Ground Floor)',
        color: '#ec4899',
        type: 'lab',
        batch: 'A1',
        division: 'Division A',
        notes: 'Batch A1 competitive algorithmic optimizations',
      },
      {
        id: 'a_tue_lab_a2',
        day: 'Tuesday',
        startTime: '14:00',
        endTime: '16:00',
        subject: 'Cyber Security & Cryptography Lab',
        subjectCode: 'CS420L',
        faculty: 'Prof. Alan Thorne',
        room: 'Grace Hopper Lab (Ground Floor)',
        color: '#ef4444',
        type: 'lab',
        batch: 'A2',
        division: 'Division A',
        notes: 'Batch A2 ethical hacking and packet inspection',
      },
      {
        id: 'a_wed_1',
        day: 'Wednesday',
        startTime: '09:30',
        endTime: '11:00',
        subject: 'Software Engineering Practices',
        subjectCode: 'CS308',
        faculty: 'Dr. Sarah Connor',
        room: 'Room 101',
        color: '#f59e0b',
        type: 'lecture',
        division: 'Division A',
      },
    ],
  },
  {
    id: 'sample_conflict_demo',
    title: 'Timetable Conflict Demo (Prompt Example)',
    description: 'Monday 10:00 AM double booked: AI in Lab 2 & DBMS in Room 305',
    classes: [
      {
        id: 'c_demo_1',
        day: 'Monday',
        startTime: '10:00',
        endTime: '11:00',
        subject: 'Artificial Intelligence (AI)',
        subjectCode: 'CS402',
        faculty: 'Prof. Alan Thorne',
        room: 'Lab 2',
        color: '#8b5cf6',
        type: 'lab',
      },
      {
        id: 'c_demo_2',
        day: 'Monday',
        startTime: '10:00',
        endTime: '11:00',
        subject: 'Database Management Systems (DBMS)',
        subjectCode: 'CS301',
        faculty: 'Dr. Robert Vance',
        room: 'Room 305',
        color: '#3b82f6',
        type: 'lecture',
      },
      {
        id: 'c_demo_3',
        day: 'Monday',
        startTime: '11:00',
        endTime: '12:00',
        subject: 'Computer Networks (CN)',
        subjectCode: 'CS304',
        faculty: 'Dr. Elena Rostova',
        room: 'Room 201',
        color: '#10b981',
        type: 'lecture',
      },
    ],
  },
];
